sonar.projectKey=lanceheld_offline-draft
sonar.organization=lanceheld
sonar.sources=src
sonar.exclusions=**/tests/**,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.node.json
